<?php

namespace app\controllers;

use app\models\Category;
use app\models\Product;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function beforeAction( $action ) {

	    $categories = Category::findAll(['parent_id'=>0]);

	    $this->view->params['categories'] = $categories;

	    return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
    }

	/**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {

	    $categories = Category::findAll(['parent_id'=>0]);

	    return $this->render('index', compact('categories'));
    }

	public function actionCategory($id = 0) {

		$category = Category::findOne(['id'=>$id]);

		$query = Product::find()->where(['category_id'=>$category->id]);
		$countQuery = clone $query;
		$count = $countQuery->count();
		$pages = new Pagination(['totalCount' => $count]);
		$products = $query->offset($pages->offset)->limit($pages->limit)->all();

		$crumbs = [$category];
		$cat = clone $category;
		while($cat->parent_id !== 0){
			$parent = Category::findOne(['id'=>$cat->parent_id]);
			$crumbs[] = $parent;
			$cat = $parent;
		}

		return $this->render('category', compact('category', 'products', 'pages', 'crumbs', 'count'));
	}

	public function actionProduct($id = 0) {
		$product = Product::findOne(['id'=>$id]);

		$product->getInfo();

		$category = $product->category;
		$crumbs = [$category];
		$cat = clone $category;
		while($cat->parent_id !== 0){
			$parent = Category::findOne(['id'=>$cat->parent_id]);
			$crumbs[] = $parent;
			$cat = $parent;
		}

		return $this->render('product', compact('crumbs', 'product'));
	}


}
